name: Deploy Application

on:
  push:
    branches: [ main]  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'   
        


      - name: Create AWS credentials file
        run: |
          mkdir -p $HOME/.aws
          cat > $HOME/.aws/credentials << EOF
          [default]
          aws_access_key_id=$AWS_ACCESS_KEY_ID
          aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
          region=$AWS_DEFAULT_REGION
          EOF

      - name: Configure Environment Variables
        run: |
          export CDK_DEFAULT_ACCOUNT=${{ vars.CDK_DEFAULT_ACCOUNT }}
          export CDK_DEFAULT_REGION=${{ vars.CDK_DEFAULT_REGION }}

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/primeralambda && npm install

      - name: Synthesize AWS CDK stack
        run: cd $GITHUB_WORKSPACE/primeralambda && npx cdk synth

      - name: Deploy AWS CDK stack
        run: |
          echo "Deploying stack..."
          cd $GITHUB_WORKSPACE/primeralambda && npx cdk deploy --all --require-approval=never
